version: '3.8'

services:
  mechbot-core:
    build: .
    volumes:
      - ./logs:/mechbot/logs
    environment:
      - AWS_PROFILE=MechBot-Admin

  valhalla-ai:
    image: tensorflow/tensorflow:latest-gpu
    volumes:
      - ./ia:/app
    command: python /app/valhalla_ai.py

  mechbot-web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
