name: MECHBOT-9000 CI/CD

push:
on
pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[test]
    - name: Run tests
      run: |
        python -m pytest tests/ -v
    - name: Security scan
      run: |
        python -m mechmind.core.security
