name: Deploy Jekyll site to Pages

on:
  # Activa el workflow cuando hay push a la rama principal
  push:
    branches: ["main"]
  
  # Permite ejecutar manualmente desde la pestaña Actions
  workflow_dispatch:

# Configura permisos para el token GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

# Concurrencia para evitar despliegues simultáneos
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para obtener historial completo para Jekyll

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'  # Versión compatible con Jekyll
          bundler-cache: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./  # Directorio fuente de Jekyll
          destination: ./_site  # Directorio de salida

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
