name: MECHBOT-9000 Pages Deployment

on:
  push:
    branches: ["main"]
    paths:
      - 'docs/**'
      - 'static/**'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para Jekyll si lo usas
          
      - name: Setup Pages
        uses: actions/configure-pages@v5
          
      - name: Build security documentation
        run: |
          mkdir -p ./_site
          cp -r docs/* ./_site/
          echo "<html><body><h1>MECHBOT-9000 Security Portal</h1></body></html>" > ./_site/index.html
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'  # Directorio específico para Pages
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
